[workspace]
members = ["abi", "reservation", "service"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.89"
chrono = { version = "0.4.38", features = ["serde"] }
sqlx = { version = "0.8.2", features = [
    "postgres",
    "runtime-tokio",
    "tls-rustls",
    "chrono",
    "uuid",
] }
